-- Seed tax rules for all 50 US states + DC
-- These are simplified rules - consult a tax professional for production use

INSERT INTO tax_rules (state_code, invoice_type, tax_rate, c2c_exempt, w2_withholding_required, compliance_notes) VALUES
-- C2C Invoices (Business-to-Business)
('AL', 'C2C', 0.00, true, false, 'Alabama: B2B services generally exempt from sales tax'),
('AK', 'C2C', 0.00, true, false, 'Alaska: No state sales tax'),
('AZ', 'C2C', 0.00, true, false, 'Arizona: B2B professional services exempt'),
('AR', 'C2C', 0.00, true, false, 'Arkansas: B2B services generally exempt'),
('CA', 'C2C', 0.00, true, false, 'California: Professional services exempt from sales tax'),
('CO', 'C2C', 0.00, true, false, 'Colorado: B2B services generally exempt'),
('CT', 'C2C', 0.00, true, false, 'Connecticut: B2B professional services exempt'),
('DE', 'C2C', 0.00, true, false, 'Delaware: No sales tax'),
('FL', 'C2C', 0.00, true, false, 'Florida: Professional services generally exempt'),
('GA', 'C2C', 0.00, true, false, 'Georgia: B2B services generally exempt'),
('HI', 'C2C', 4.00, false, false, 'Hawaii: GET applies to services at 4%'),
('ID', 'C2C', 0.00, true, false, 'Idaho: B2B services generally exempt'),
('IL', 'C2C', 0.00, true, false, 'Illinois: Professional services exempt'),
('IN', 'C2C', 0.00, true, false, 'Indiana: Professional services exempt'),
('IA', 'C2C', 0.00, true, false, 'Iowa: B2B services generally exempt'),
('KS', 'C2C', 0.00, true, false, 'Kansas: B2B services generally exempt'),
('KY', 'C2C', 0.00, true, false, 'Kentucky: Professional services exempt'),
('LA', 'C2C', 0.00, true, false, 'Louisiana: B2B services generally exempt'),
('ME', 'C2C', 0.00, true, false, 'Maine: Professional services exempt'),
('MD', 'C2C', 0.00, true, false, 'Maryland: Professional services exempt'),
('MA', 'C2C', 0.00, true, false, 'Massachusetts: Professional services exempt'),
('MI', 'C2C', 0.00, true, false, 'Michigan: Professional services exempt'),
('MN', 'C2C', 0.00, true, false, 'Minnesota: Professional services exempt'),
('MS', 'C2C', 0.00, true, false, 'Mississippi: Professional services exempt'),
('MO', 'C2C', 0.00, true, false, 'Missouri: Professional services exempt'),
('MT', 'C2C', 0.00, true, false, 'Montana: No sales tax'),
('NE', 'C2C', 0.00, true, false, 'Nebraska: Professional services exempt'),
('NV', 'C2C', 0.00, true, false, 'Nevada: Professional services exempt'),
('NH', 'C2C', 0.00, true, false, 'New Hampshire: No sales tax'),
('NJ', 'C2C', 0.00, true, false, 'New Jersey: Professional services exempt'),
('NM', 'C2C', 5.00, false, false, 'New Mexico: GRT applies to professional services'),
('NY', 'C2C', 0.00, true, false, 'New York: Professional services exempt'),
('NC', 'C2C', 0.00, true, false, 'North Carolina: Professional services exempt'),
('ND', 'C2C', 0.00, true, false, 'North Dakota: Professional services exempt'),
('OH', 'C2C', 0.00, true, false, 'Ohio: Professional services exempt'),
('OK', 'C2C', 0.00, true, false, 'Oklahoma: Professional services exempt'),
('OR', 'C2C', 0.00, true, false, 'Oregon: No sales tax'),
('PA', 'C2C', 0.00, true, false, 'Pennsylvania: Professional services exempt'),
('RI', 'C2C', 0.00, true, false, 'Rhode Island: Professional services exempt'),
('SC', 'C2C', 0.00, true, false, 'South Carolina: Professional services exempt'),
('SD', 'C2C', 4.50, false, false, 'South Dakota: Services taxable at 4.5%'),
('TN', 'C2C', 0.00, true, false, 'Tennessee: Professional services exempt'),
('TX', 'C2C', 0.00, true, false, 'Texas: Professional services exempt'),
('UT', 'C2C', 0.00, true, false, 'Utah: Professional services exempt'),
('VT', 'C2C', 0.00, true, false, 'Vermont: Professional services exempt'),
('VA', 'C2C', 0.00, true, false, 'Virginia: Professional services exempt'),
('WA', 'C2C', 0.00, true, false, 'Washington: B&O tax applies separately'),
('WV', 'C2C', 6.00, false, false, 'West Virginia: Services taxable at 6%'),
('WI', 'C2C', 0.00, true, false, 'Wisconsin: Professional services exempt'),
('WY', 'C2C', 0.00, true, false, 'Wyoming: Professional services exempt'),
('DC', 'C2C', 0.00, true, false, 'DC: Professional services exempt'),

-- W2 Employee Invoices (placeholder rates - actual withholding varies)
('AL', 'W2', 5.00, false, true, 'Alabama: State income tax withholding required'),
('AK', 'W2', 0.00, false, false, 'Alaska: No state income tax'),
('AZ', 'W2', 2.59, false, true, 'Arizona: State income tax withholding required'),
('AR', 'W2', 5.50, false, true, 'Arkansas: State income tax withholding required'),
('CA', 'W2', 9.30, false, true, 'California: State income tax withholding required'),
('CO', 'W2', 4.40, false, true, 'Colorado: Flat tax withholding required'),
('CT', 'W2', 5.00, false, true, 'Connecticut: State income tax withholding required'),
('DE', 'W2', 6.60, false, true, 'Delaware: State income tax withholding required'),
('FL', 'W2', 0.00, false, false, 'Florida: No state income tax'),
('GA', 'W2', 5.49, false, true, 'Georgia: State income tax withholding required'),
('HI', 'W2', 8.25, false, true, 'Hawaii: State income tax withholding required'),
('ID', 'W2', 5.80, false, true, 'Idaho: State income tax withholding required'),
('IL', 'W2', 4.95, false, true, 'Illinois: Flat tax withholding required'),
('IN', 'W2', 3.05, false, true, 'Indiana: Flat tax withholding required'),
('IA', 'W2', 5.70, false, true, 'Iowa: State income tax withholding required'),
('KS', 'W2', 5.70, false, true, 'Kansas: State income tax withholding required'),
('KY', 'W2', 4.00, false, true, 'Kentucky: Flat tax withholding required'),
('LA', 'W2', 4.25, false, true, 'Louisiana: State income tax withholding required'),
('ME', 'W2', 7.15, false, true, 'Maine: State income tax withholding required'),
('MD', 'W2', 5.75, false, true, 'Maryland: State income tax withholding required'),
('MA', 'W2', 5.00, false, true, 'Massachusetts: Flat tax withholding required'),
('MI', 'W2', 4.25, false, true, 'Michigan: Flat tax withholding required'),
('MN', 'W2', 7.85, false, true, 'Minnesota: State income tax withholding required'),
('MS', 'W2', 5.00, false, true, 'Mississippi: State income tax withholding required'),
('MO', 'W2', 4.95, false, true, 'Missouri: State income tax withholding required'),
('MT', 'W2', 6.75, false, true, 'Montana: State income tax withholding required'),
('NE', 'W2', 6.64, false, true, 'Nebraska: State income tax withholding required'),
('NV', 'W2', 0.00, false, false, 'Nevada: No state income tax'),
('NH', 'W2', 0.00, false, false, 'New Hampshire: No wage income tax'),
('NJ', 'W2', 8.97, false, true, 'New Jersey: State income tax withholding required'),
('NM', 'W2', 5.90, false, true, 'New Mexico: State income tax withholding required'),
('NY', 'W2', 8.82, false, true, 'New York: State income tax withholding required'),
('NC', 'W2', 4.75, false, true, 'North Carolina: Flat tax withholding required'),
('ND', 'W2', 2.50, false, true, 'North Dakota: State income tax withholding required'),
('OH', 'W2', 3.99, false, true, 'Ohio: State income tax withholding required'),
('OK', 'W2', 4.75, false, true, 'Oklahoma: State income tax withholding required'),
('OR', 'W2', 9.00, false, true, 'Oregon: State income tax withholding required'),
('PA', 'W2', 3.07, false, true, 'Pennsylvania: Flat tax withholding required'),
('RI', 'W2', 5.99, false, true, 'Rhode Island: State income tax withholding required'),
('SC', 'W2', 6.40, false, true, 'South Carolina: State income tax withholding required'),
('SD', 'W2', 0.00, false, false, 'South Dakota: No state income tax'),
('TN', 'W2', 0.00, false, false, 'Tennessee: No wage income tax'),
('TX', 'W2', 0.00, false, false, 'Texas: No state income tax'),
('UT', 'W2', 4.65, false, true, 'Utah: Flat tax withholding required'),
('VT', 'W2', 8.75, false, true, 'Vermont: State income tax withholding required'),
('VA', 'W2', 5.75, false, true, 'Virginia: State income tax withholding required'),
('WA', 'W2', 0.00, false, false, 'Washington: No state income tax'),
('WV', 'W2', 6.50, false, true, 'West Virginia: State income tax withholding required'),
('WI', 'W2', 7.65, false, true, 'Wisconsin: State income tax withholding required'),
('WY', 'W2', 0.00, false, false, 'Wyoming: No state income tax'),
('DC', 'W2', 8.50, false, true, 'DC: Income tax withholding required'),

-- 1099 Contractor Invoices (self-employment considerations)
('AL', '1099', 0.00, true, false, 'Alabama: 1099 contractors responsible for own taxes'),
('AK', '1099', 0.00, true, false, 'Alaska: No state income tax'),
('AZ', '1099', 0.00, true, false, 'Arizona: 1099 contractors responsible for own taxes'),
('AR', '1099', 0.00, true, false, 'Arkansas: 1099 contractors responsible for own taxes'),
('CA', '1099', 0.00, true, false, 'California: 1099 contractors responsible for own taxes'),
('CO', '1099', 0.00, true, false, 'Colorado: 1099 contractors responsible for own taxes'),
('CT', '1099', 0.00, true, false, 'Connecticut: 1099 contractors responsible for own taxes'),
('DE', '1099', 0.00, true, false, 'Delaware: 1099 contractors responsible for own taxes'),
('FL', '1099', 0.00, true, false, 'Florida: No state income tax'),
('GA', '1099', 0.00, true, false, 'Georgia: 1099 contractors responsible for own taxes'),
('HI', '1099', 4.00, false, false, 'Hawaii: GET may apply to contractor services'),
('ID', '1099', 0.00, true, false, 'Idaho: 1099 contractors responsible for own taxes'),
('IL', '1099', 0.00, true, false, 'Illinois: 1099 contractors responsible for own taxes'),
('IN', '1099', 0.00, true, false, 'Indiana: 1099 contractors responsible for own taxes'),
('IA', '1099', 0.00, true, false, 'Iowa: 1099 contractors responsible for own taxes'),
('KS', '1099', 0.00, true, false, 'Kansas: 1099 contractors responsible for own taxes'),
('KY', '1099', 0.00, true, false, 'Kentucky: 1099 contractors responsible for own taxes'),
('LA', '1099', 0.00, true, false, 'Louisiana: 1099 contractors responsible for own taxes'),
('ME', '1099', 0.00, true, false, 'Maine: 1099 contractors responsible for own taxes'),
('MD', '1099', 0.00, true, false, 'Maryland: 1099 contractors responsible for own taxes'),
('MA', '1099', 0.00, true, false, 'Massachusetts: 1099 contractors responsible for own taxes'),
('MI', '1099', 0.00, true, false, 'Michigan: 1099 contractors responsible for own taxes'),
('MN', '1099', 0.00, true, false, 'Minnesota: 1099 contractors responsible for own taxes'),
('MS', '1099', 0.00, true, false, 'Mississippi: 1099 contractors responsible for own taxes'),
('MO', '1099', 0.00, true, false, 'Missouri: 1099 contractors responsible for own taxes'),
('MT', '1099', 0.00, true, false, 'Montana: No sales tax'),
('NE', '1099', 0.00, true, false, 'Nebraska: 1099 contractors responsible for own taxes'),
('NV', '1099', 0.00, true, false, 'Nevada: No state income tax'),
('NH', '1099', 0.00, true, false, 'New Hampshire: No wage income tax'),
('NJ', '1099', 0.00, true, false, 'New Jersey: 1099 contractors responsible for own taxes'),
('NM', '1099', 5.00, false, false, 'New Mexico: GRT may apply to contractor services'),
('NY', '1099', 0.00, true, false, 'New York: 1099 contractors responsible for own taxes'),
('NC', '1099', 0.00, true, false, 'North Carolina: 1099 contractors responsible for own taxes'),
('ND', '1099', 0.00, true, false, 'North Dakota: 1099 contractors responsible for own taxes'),
('OH', '1099', 0.00, true, false, 'Ohio: 1099 contractors responsible for own taxes'),
('OK', '1099', 0.00, true, false, 'Oklahoma: 1099 contractors responsible for own taxes'),
('OR', '1099', 0.00, true, false, 'Oregon: No sales tax'),
('PA', '1099', 0.00, true, false, 'Pennsylvania: 1099 contractors responsible for own taxes'),
('RI', '1099', 0.00, true, false, 'Rhode Island: 1099 contractors responsible for own taxes'),
('SC', '1099', 0.00, true, false, 'South Carolina: 1099 contractors responsible for own taxes'),
('SD', '1099', 4.50, false, false, 'South Dakota: Services taxable at 4.5%'),
('TN', '1099', 0.00, true, false, 'Tennessee: No wage income tax'),
('TX', '1099', 0.00, true, false, 'Texas: No state income tax'),
('UT', '1099', 0.00, true, false, 'Utah: 1099 contractors responsible for own taxes'),
('VT', '1099', 0.00, true, false, 'Vermont: 1099 contractors responsible for own taxes'),
('VA', '1099', 0.00, true, false, 'Virginia: 1099 contractors responsible for own taxes'),
('WA', '1099', 0.00, true, false, 'Washington: B&O tax may apply separately'),
('WV', '1099', 6.00, false, false, 'West Virginia: Services may be taxable at 6%'),
('WI', '1099', 0.00, true, false, 'Wisconsin: 1099 contractors responsible for own taxes'),
('WY', '1099', 0.00, true, false, 'Wyoming: No state income tax'),
('DC', '1099', 0.00, true, false, 'DC: 1099 contractors responsible for own taxes')
ON CONFLICT (state_code, invoice_type) DO UPDATE SET
  tax_rate = EXCLUDED.tax_rate,
  c2c_exempt = EXCLUDED.c2c_exempt,
  w2_withholding_required = EXCLUDED.w2_withholding_required,
  compliance_notes = EXCLUDED.compliance_notes,
  updated_at = CURRENT_TIMESTAMP;
